// Deutsche Bezeichnungen für Aktionstypen im Protokoll-Viewer

import { A } from '@/core/actions'

export const ACTION_LABELS: Record<string, string> = {
  [A.ticketCreated]: 'Ticket erstellt',
  [A.ticketClaimed]: 'Ticket übernommen',
  [A.ticketUpdated]: 'Ticket geändert',
  [A.ticketStatus]: 'Ticketstatus geändert',
  [A.ticketWorkNote]: 'Arbeitsnotiz',
  [A.ticketComment]: 'Kommentar an Benutzer',
  [A.ticketEscalated]: 'Ticket eskaliert',
  [A.ticketResolved]: 'Ticket gelöst',
  [A.hintUsed]: 'Tipp verwendet',
  [A.identityAsked]: 'Identität abgefragt',
  [A.identityConfirmed]: 'Identität genannt',
  [A.confirmAsked]: 'Lösung bestätigen lassen',
  [A.userConfirmedFix]: 'Benutzer bestätigt Lösung',
  [A.mailSent]: 'E-Mail gesendet',
  [A.chatSent]: 'Chatnachricht',
  [A.callAccepted]: 'Anruf angenommen',
  [A.callEnded]: 'Anruf beendet',
  [A.callOutgoing]: 'Ausgehender Anruf',
  [A.secretShared]: 'Vertrauliches übermittelt',
  [A.remoteConsent]: 'Einverständnis Fernzugriff',
  [A.userInformed]: 'Benutzer informiert',
  [A.adUnlock]: 'AD: Konto entsperrt',
  [A.adPasswordReset]: 'AD: Kennwort zurückgesetzt',
  [A.adUserCreated]: 'AD: Benutzer angelegt',
  [A.adUserUpdated]: 'AD: Benutzer geändert',
  [A.adUserEnabled]: 'AD: Konto aktiviert',
  [A.adUserDisabled]: 'AD: Konto deaktiviert',
  [A.adUserMoved]: 'AD: Objekt verschoben',
  [A.adUserDeleted]: 'AD: Benutzer gelöscht',
  [A.adGroupAdd]: 'AD: Gruppenmitglied hinzugefügt',
  [A.adGroupRemove]: 'AD: Gruppenmitglied entfernt',
  [A.adGroupCreated]: 'AD: Gruppe angelegt',
  [A.adComputerReset]: 'AD: Computerkonto zurückgesetzt',
  [A.adComputerUpdated]: 'AD: Computer geändert',
  [A.adBitlockerViewed]: 'AD: BitLocker-Schlüssel angezeigt',
  [A.adLapsViewed]: 'AD: LAPS-Kennwort angezeigt',
  [A.cloudLicenseAssigned]: 'Cloud: Lizenz zugewiesen',
  [A.cloudLicenseRemoved]: 'Cloud: Lizenz entfernt',
  [A.cloudMfaReset]: 'Cloud: MFA zurückgesetzt',
  [A.cloudSignInBlocked]: 'Cloud: Anmeldung blockiert',
  [A.cloudSignInUnblocked]: 'Cloud: Anmeldung freigegeben',
  [A.cloudSessionsRevoked]: 'Cloud: Sitzungen widerrufen',
  [A.cloudMailboxPermission]: 'Cloud: Postfachberechtigung',
  [A.cloudMailboxUpdated]: 'Cloud: Postfach geändert',
  [A.cloudPasswordReset]: 'Cloud: Kennwort zurückgesetzt',
  [A.cloudSync]: 'Cloud: Synchronisierung',
  [A.cloudSenderBlocked]: 'Cloud: Absender gesperrt',
  [A.cloudQuarantine]: 'Cloud: Quarantäne',
  [A.rdpConnected]: 'Remote-Desktop verbunden',
  [A.rdpDisconnected]: 'Remote-Desktop getrennt',
  [A.command]: 'Befehl ausgeführt',
  [A.serviceChanged]: 'Dienst geändert',
  [A.processKilled]: 'Prozess beendet',
  [A.networkChanged]: 'Netzwerk geändert',
  [A.printerChanged]: 'Drucker geändert',
  [A.registryChanged]: 'Registry geändert',
  [A.fileChanged]: 'Datei geändert',
  [A.diskChanged]: 'Datenträger geändert',
  [A.deviceChanged]: 'Gerät geändert',
  [A.reboot]: 'Neustart',
  [A.gpupdate]: 'Gruppenrichtlinien aktualisiert',
  [A.dhcpChanged]: 'DHCP geändert',
  [A.dnsChanged]: 'DNS geändert',
  [A.shareChanged]: 'Freigabe geändert',
  [A.printQueueChanged]: 'Druckwarteschlange geändert',
  [A.printerDeviceChanged]: 'Druckergerät geändert',
  [A.serverServiceChanged]: 'Serverdienst geändert',
  [A.assetAssigned]: 'Asset zugewiesen',
  [A.assetUpdated]: 'Asset geändert',
  [A.shipmentCreated]: 'Sendung angelegt',
  [A.shipmentUpdated]: 'Sendung aktualisiert',
  [A.kbViewed]: 'KB-Artikel gelesen',
  [A.kbCreated]: 'KB-Artikel erstellt',
  [A.kbLinked]: 'KB-Artikel verknüpft',
  'kb.updated': 'KB-Artikel bearbeitet',
  [A.browserVisit]: 'Webseite aufgerufen',
}

export const actionLabel = (type: string) => ACTION_LABELS[type] ?? type

/** Bereich eines Aktionstyps (Präfix vor dem Punkt) */
export const AREA_LABELS: Record<string, string> = {
  ticket: 'Tickets',
  comm: 'Kommunikation',
  ad: 'Active Directory',
  cloud: 'Cloud',
  rdp: 'Remote-Desktop',
  endpoint: 'Endpunkte',
  infra: 'Infrastruktur',
  asset: 'Inventar',
  shipment: 'Versand',
  kb: 'Wissen',
  browser: 'Browser',
}

/** Aktionen, die für die Bewertung besonders relevant sind (farblich hervorheben) */
export const SENSITIVE_TYPES = new Set<string>([A.adPasswordReset, A.cloudMfaReset, A.adBitlockerViewed, A.cloudPasswordReset, A.adLapsViewed, A.secretShared, A.hintUsed])
export const GOOD_TYPES = new Set<string>([A.identityAsked, A.confirmAsked, A.remoteConsent, A.userInformed, A.ticketClaimed])
